version: "2"
networks:
  monitoring:
services:
  uwsgi-nginx:
    image: tiangolo/uwsgi-nginx:python3.7
    container_name: uwsgi-nginx
    restart: always
    ports:
      - 8080:8080
    networks:
      - monitoring
    environment:
      - LISTEN_PORT=8080
#  influxdb:
#    image: influxdb
#    container_name: influxdb
#    restart: always
#    ports:
#      - 8086:8086
#    networks:
#      - monitoring
#    volumes:
#      - influxdb-volume:/var/lib/influxdb
#  nginx:
#    image: nginx:latest
#    container_name: nginx
#    volumes:
#      - ./mysite.template:/etc/nginx/conf.d/mysite.template
#      - ./nginx/logs:/etc/nginx/logs
##      - ./nginx/html:/etc/nginx/html
#    restart: always
#    networks:
#      - monitoring
#    ports:
#      - 8080:80
#    environment:
#      - NGINX_HOST=localhost
#      - NGINX_PORT=80
#    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
#volumes:
#  grafana-volume:
##    external: true
#  influxdb-volume:
##    external: true